version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style & correctness
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - nilerr
    - errorlint
    - copyloopvar

    # Security
    - gosec

  disable:
    # Too noisy for Terraform provider code
    - exhaustruct

  settings:
    gosec:
      excludes:
        - G107 # URL provided by variable — expected in API client code

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  exclusions:
    rules:
      # Test files can be more relaxed
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - unparam

      # Generated code should not be linted
      - path: internal/provider/generated/
        linters:
          - gofmt

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/darshan-rambhia/terraform-provider-arcane

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
